
notifications:
  email: false

language: cpp
dist: xenial
matrix:
  include:
    - os: linux
      env: PYTHON=3.6 COMPILER=clang++-7
      addons: &clang70
        apt:
          packages:
            - clang-7
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
    - os: linux
      env: PYTHON=3.6 COMPILER=g++-7
      addons: &gcc7
        apt:
          packages: g++-7
          sources:
            - ubuntu-toolchain-r-test
    - os: linux
      env: CONDA=3.6
before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
  if [ -n "$PYTHON" ]; then
    python -m pip install --user virtualenv
    virtualenv -p python${PYTHON:0:1} venv
    source venv/bin/activate
  elif [ -n "$CONDA" ]; then
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then OS=Linux-x86_64; else OS=MacOSX-x86_64; fi
    wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda${CONDA:0:1}-latest-$OS.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no
    conda config --add channels conda-forge
    conda update -q conda
    conda install -q pip git
    conda create -q -n test-environment python=$CONDA
    source activate test-environment
  fi
install:
- |
  if [ -n "$PYTHON" ]; then
    python setup.py sdist
    python -m pip install 'pybind11>=2.3'
    python -m pip install --verbose dist/*.tar.gz
    python -m pip install git+https://git@github.com/vatj/integer_polyomino.git
  elif [ -n "$CONDA" ]; then
    pip install git+https://git@github.com/vatj/integer_polyomino.git
  fi
