
notifications:
  email: false

language: cpp
dist: bionic

matrix:
  include:
    - os: linux
      env: PYTHON=3.6 CXX=g++ CC=gcc
before_install:
- |
  python -m pip install --user virtualenv
  virtualenv -p python${PYTHON:0:1} venv
  source venv/bin/activate
install:
- |
  if [ -n "$PYTHON" ]; then
    python -m pip install git+https://git@github.com/vatj/gpmap_integer_polyomino.git
  elif [ -n "$CONDA" ]; then
    pip install git+https://git@github.com/vatj/gpmap_integer_polyomino.git
  fi
script:
- |
  python -m pip show integer_polyomino
